image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Install mimics-binary
        script:
          - wget https://artifacts.rapid7.com/cloudsec/mimics/latest/mimics_latest_linux_amd64 -O mimics
          - chmod +x mimics
        artifacts:
          - mimics

    - step:
        name: Install and initialize Terraform
        script:
          - if [ ! -f /usr/local/bin/terraform ]; then
              curl -LO https://releases.hashicorp.com/terraform/0.14.11/terraform_0.14.11_linux_arm64.zip;
              unzip terraform_0.14.11_linux_arm64.zip -d terraform_temp;
              chmod +x terraform_temp/terraform;
              mv terraform_temp/terraform /usr/local/bin/;
            else
              mv /usr/local/bin/terraform /usr/local/bin/terraform.old;
              curl -LO https://releases.hashicorp.com/terraform/0.14.11/terraform_0.14.11_linux_arm64.zip;
              unzip terraform_0.14.11_linux_arm64.zip -d terraform_temp;
              chmod +x terraform_temp/terraform;
              mv terraform_temp/terraform /usr/local/bin/;
            fi
        artifacts:
          - terraform

    - step:
        name: Scan IaC files with mimics
        script:
          - ./mimics scan "$BITBUCKET_CLONE_DIR" --api-key "$API_KEY" --base-url "$BASE_URL" --no-verify --log-format json --report-formats all --report-name probe --save-report --no-fail --verbose
        artifacts:
          - "probe.*"
